# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Landhiani
tagline:          'Personal Blog Landhiani'
description:      'I'm a writer based in Indonesia. I love to create content not just for search engine, but also for you :)' 
url:              https://landhiani.github.io
baseurl:          /

author:
  name:           'Justin'
  url:            https://twitter.com/jsticious_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
